environments:
  local:
    values:
      - helm/environments/local.yaml
  dev:
    values:
      - helm/environments/dev.yaml
  prod:
    values:
      - helm/environments/prod.yaml

---

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:

  ## Namespace ##

  - name: namespace
    chart: ./helm/charts/namespace
    namespace: default

  ## Cert-manager ##

  - name: certs-manager
    chart: ./helm/charts/certs-manager
    namespace: networking
    needs: [namespace]

  ## Gateway API ##

  # Install the Gateway API CRDs and Envoy Gateway Controller
  - name: envoy-controller
    chart: ./helm/charts/gateway-controller
    namespace: networking
    needs: [namespace]

  # Install the Envoy Gateway Class and bind to the Envoy controller
  - name: gateway-class
    chart: ./helm/charts/gateway-class
    namespace: networking
    needs: [namespace, networking/envoy-controller]

  # Install the Envoy Gateway
  - name: gateway
    chart: ./helm/charts/gateway
    namespace: networking
    needs: [namespace, networking/certs-manager, networking/gateway-class]

    values:
      - helm/environments/{{ .Environment.Name }}.yaml