# global
global:
  environment: dev

# gateway
gateway:
  tls:
    enabled: true
    selfSigned: false
  hosts:
    domain: "test.de"
    email: "test@test.de"
  nodePort:
    enabled: false
  timeout:
    requestTimeout: 1800s
