# global
global:
  environment: local

# gateway
gateway:
  tls:
    enabled: true
    selfSigned: true
  hosts:
    domain: ""
    email: ""
  nodePort:
    enabled: true
    http: 32080
    https: 32443
  timeout:
    requestTimeout: 1800s
