apiVersion: v2
name: gateway-controller
version: 0.1.0
description: Envoy Gateway controller and GatewayClass
dependencies:
  - name: gateway-helm
    version: 1.4.0
    repository: oci://docker.io/envoyproxy
